baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Rin'
theme = "gruvhugo" 

# Default Post Extension
defaultExtension= "html"

# Default metadata format for newly created frontmatter using
# hugo new command. "toml", "yaml", or "json"
metaDataFormat= "yaml"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  enableKatex = true
  metaKeywords = "fast, hugo, theme, minimal, gruvbox"
  headerTitle = "Rin"
  copyright = "© 2021 No767. Website licensed under Apache-2.0, project licensed under CC0-1.0"
  name = "Rin"
  img = "img/author.jpg"
  # Thanks to Christina @ wocintechchat.com for this photo.
  icon = "img/logo.png"
  quote = "A Discord bot with EasyBot.py plugin support and additional features"
  description= "Discord bots have been present for quite some time, and have been for some time. Rin is designed to be a easy-to-use discord bot that is based off of Chisaku's EasyBot.py project. It is meant as a general-purpose bot, which uses third-party APIs to obtain posts, and content. As of now, it is alpha, and is not ready for production use."
  licenseUrl = "https://github.com/No767/Rin/blob/master/LICENSE"

 # Social icons
  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/No767"

  [[params.social]]
    name = "github"
    url  = "https://github.com/No767"


[menu]
  [[menu.main]]
    identifier = "about"
    name       = "GitHub"
    url        = "https://github.com/No767/Rin"

  [[menu.main]]
    identifier = "posts"
    name       = "Docs"
    url        = "https://rin-docs.readthedocs.io/en/latest/"

  [[menu.main]]
    identifier = "wiki"
    name       = "Homepage"
    url        = "none"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
    docType = "article"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = true
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
